# Schema for configuration files of the Cookie Information module.

cookieinformation.settings:
  type: config_object
  label: 'Cookie Information settings'
  mapping:
    enable_popup:
      type: boolean
      label: 'Enable the cookie consent popup.'
    enable_iab:
      type: boolean
      label: 'Enable the IAB cookie consent popup.'
    exclude_paths:
      type: string
      label: 'Exclude paths.'
    exclude_admin:
      type: boolean
      label: 'Exclude admin routes.'
    exclude_uid_1:
      type: boolean
      label: 'Exclude user 1.'
